"""Markdown blocks: split a sprint file into editable pieces, and back again.

Pure functions only: no database, no framework, no I/O. The sprint editor is a
view over `sprints/NN.md`; the file on disk stays the one record, so nothing
here parses markdown into sprint concepts and nothing here stores anything.

A **block** is one top-level markdown construct -- a heading, a paragraph, a
list, a table, a fence, a quote, a rule, or an HTML island -- carrying its own
raw source:

    index: position in the document, from 0
    type:  one of BLOCK_TYPES
    raw:   the block's markdown, with no trailing line ending
    gap:   the exact text between this block and the next (its own line ending
           plus any blank lines), so the document can be rebuilt byte for byte
    html:  rendered for **display only**, attached by `document_blocks`
    table: head/align/rows, on table blocks only

Nothing is ever parsed back out of `html`. `raw` is authoritative for every type
except `table`, where the grid is authoritative and `raw` is regenerated by
`serialise_table`.

Two invariants live here specifically:

  1. **Prose is never rewritten.** ``join_blocks(split_blocks(t)) == t`` byte
     for byte: every line of the input belongs to exactly one block's `raw` or
     one block's `gap`. Each block keeps its own source, so the serialiser for
     prose is the identity function and there is no markdown -> AST -> markdown
     round trip to normalise anything. Tables are this module's single exception,
     and only when the grid was edited -- `serialise_table` aligns the columns it
     writes, which is the feature that motivated the editor.

     One exception lives **outside** this module and is worth knowing about here:
     the editor's inline surfaces are `contenteditable`, so a block someone typed
     in has its inline source written back from the DOM by `inlineMarkdown` in
     `editor.js`. Constructs that renderer knows are respelled canonically
     (`<b>x</b>` becomes `**x**`); everything it does not know passes through as
     text, and a block nobody touched is untouched. Nothing on this side changes:
     what arrives to be saved is still whole-file text, split by the same
     splitter.
  2. **This module is sprint-agnostic.** It never learns what a capacity table
     is. Any pipe table gets the same treatment, no category is validated and no
     point is counted. That is the condition the sprint-4 gate override rests
     on: an editor that knows nothing about sprint sections cannot commit the
     storage question early.

The block boundaries are found by hand rather than taken from a parser's token
stream, and that is safe because **the failure mode is benign**: a boundary in
the wrong place reveals a bigger chunk of raw text than ideal when you click it.
It cannot lose or rewrite content, because it never rewrote it in the first
place.
"""

import re
from html import escape

from markdown_it import MarkdownIt
from markdown_it.renderer import RendererHTML
from mdit_py_plugins.tasklists import tasklists_plugin

BLOCK_TYPES = (
    "heading",
    "paragraph",
    "list",
    "table",
    "code",
    "quote",
    "rule",
    "html",
)

# What separates two blocks when a caller builds a block list itself -- the
# frontend inserting a new block has no gap to preserve. Blocks that came from
# `split_blocks` carry their own.
DEFAULT_GAP = "\n\n"

# The narrowest column `serialise_table` will write, so a `---` delimiter still
# reads as one and a `:---:` has room for both markers.
MIN_COLUMN_WIDTH = 3

# How a line break inside a cell is written to the file. A GFM cell is inline
# content and cannot hold a real newline -- and a newline in a pipe row *is* a
# new row, so writing one would split the table silently. `cellText` in
# `editor.js` reads this back into a newline, the same contract `MERMAID_CLASS`
# has with that file: the string is the whole agreement between the two.
CELL_BREAK = "<br>"

_BLANK = re.compile(r"^[ \t]*\r?\n?$")
_ATX = re.compile(r"^ {0,3}#{1,6}([ \t]|$)")
_FENCE = re.compile(r"^ {0,3}(`{3,}|~{3,})")
_RULE = re.compile(r"^ {0,3}(?:(?:-[ \t]*){3,}|(?:\*[ \t]*){3,}|(?:_[ \t]*){3,})\r?\n?$")
_SETEXT = re.compile(r"^ {0,3}(=+|-+)[ \t]*\r?\n?$")
_BULLET = re.compile(r"^ {0,3}[-*+][ \t]")
_ORDERED = re.compile(r"^ {0,3}\d{1,9}[.)][ \t]")
_QUOTE = re.compile(r"^ {0,3}>")
_HTML_COMMENT = re.compile(r"^ {0,3}<!--")
_HTML_TAG = re.compile(r"^ {0,3}</?[A-Za-z][A-Za-z0-9-]*")
_INDENTED = re.compile(r"^([ ]{2,}|\t)")
_DELIMITER_CELL = re.compile(r"^:?-+:?$")
_UNESCAPED_PIPE = re.compile(r"(?<!\\)\|")
# Any line ending a grid cell can arrive with, CRLF first so it becomes one break.
_CELL_NEWLINE = re.compile(r"\r\n|[\r\n]")


# --- reading the document ---------------------------------------------------


def split_blocks(text):
    """Split markdown into blocks that rebuild the input exactly.

    Boundaries only -- nothing is rendered and nothing is reformatted. Blank
    lines ride on the preceding block's `gap`; a blank run at the very start of
    the file has no preceding block, so it rides on the front of the first
    block's `raw` instead.
    """
    lines = text.splitlines(keepends=True)
    blocks = []
    prefix = ""
    index = 0
    i = 0

    while i < len(lines):
        if _is_blank(lines[i]):
            # Before the first block there is no gap to attach this to.
            prefix += lines[i]
            i += 1
            continue

        end, kind = _consume(lines, i)
        raw, gap = _split_trailing_newline("".join(lines[i:end]))
        i = end
        while i < len(lines) and _is_blank(lines[i]):
            gap += lines[i]
            i += 1

        block = {"index": index, "type": kind, "raw": prefix + raw, "gap": gap}
        table = parse_table(raw) if kind == "table" else None
        if table:
            block["table"] = table
        blocks.append(block)
        prefix = ""
        index += 1

    if prefix:
        # An all-whitespace document. Keep it rather than silently emptying it.
        blocks.append({"index": 0, "type": "paragraph", "raw": prefix, "gap": ""})
    return blocks


def join_blocks(blocks):
    """Rebuild a document from blocks, using each block's own gap."""
    return "".join(block["raw"] + block.get("gap", DEFAULT_GAP) for block in blocks)


# --- writing one run of blocks ----------------------------------------------
#
# A whole-file save replaces the document. `splice_blocks` replaces a contiguous
# run of blocks inside it and leaves every other byte alone, so two writes to
# different parts of one file are not a conflict. It is still text in, text out:
# nothing here is stored, and the file remains the one record.
#
# The run is named by **where the caller thinks it is and what it thinks it
# says** -- `at` plus the raw text of each block. Nothing in the file names a
# block, and the three other ways to give it a name were rejected: position
# alone silently lands on the wrong paragraph after one insert above, ids
# written into the file stop it being clean markdown, and a sidecar id map is a
# second store that goes stale the moment a file is edited outside the app.


class SpliceRefused(Exception):
    """A run of blocks could not be placed. `reason` says which way.

    Three ways, all of them "the document is not what the caller believed":
    `gone` (nothing matches), `ambiguous` (more than one place matches), and
    `out of range` (an insert anchored past either end). Never raised when the
    run can be placed in exactly one place -- so the only outcomes a caller has
    to handle are "the right block" and "refused".
    """

    def __init__(self, reason, detail):
        super().__init__(detail)
        self.reason = reason
        self.detail = detail


def find_run(blocks, at, expect):
    """Index where the run `expect` sits in `blocks`. Refuses if that is not one place.

    Tried in order: the run at `at`, then a search of the whole document. The
    search is what lets a write survive someone inserting a heading above it --
    the block moved, the write still lands on that block. Two identical blocks
    are genuinely ambiguous and are refused rather than guessed at: a reload
    costs a moment, a write on the wrong line costs trust in the file.
    """
    raws = [block["raw"] for block in blocks]
    width = len(expect)

    # An empty run matches everywhere, so `at` is the only anchor it has.
    if width == 0:
        if not 0 <= at <= len(raws):
            raise SpliceRefused(
                "out of range",
                f"Cannot insert at block {at}: the document has {len(raws)}.",
            )
        return at

    if 0 <= at <= len(raws) - width and raws[at:at + width] == expect:
        return at

    found = [i for i in range(len(raws) - width + 1) if raws[i:i + width] == expect]
    if len(found) == 1:
        return found[0]
    if not found:
        raise SpliceRefused("gone", "That block is not in the file any more.")
    raise SpliceRefused(
        "ambiguous",
        f"{len(found)} blocks in the file say exactly that, so which one was meant is a guess.",
    )


def splice_blocks(text, at, expect, blocks):
    """Replace the run matching `expect` with `blocks`. Returns `(text, at)`.

    One operation covers all five edits: replace is 1->1, split 1->2, merge
    2->1, insert 0->1 (`expect` empty) and delete 1->0 (`blocks` empty). `at` is
    where the caller believes the run starts; the returned index is where it was
    actually applied, which differs when the run had moved.

    Gaps: a replacement block may name its own `gap`, and the trailing line
    ending of its `raw` counts as naming one. Otherwise the server supplies it,
    so a caller that forgets cannot silently reflow the file -- the last block of
    the run keeps the gap the run had, and the rest get `DEFAULT_GAP`.

    **The document's own ending belongs to the document, not to a block.** A
    splice at the end of the file preserves the bytes the file ended with,
    which is the one case where a byte outside the replaced run moves.
    """
    current = split_blocks(text)
    index = find_run(current, at, expect)
    end = index + len(expect)

    head = [dict(block) for block in current[:index]]
    tail = [dict(block) for block in current[end:]]
    new = [_incoming(block) for block in blocks]

    # What separated the run from what follows it separates the replacement from
    # the same thing -- so a caller that named no gap cannot reflow the file.
    if expect and new and new[-1]["gap"] is None:
        new[-1]["gap"] = current[end - 1]["gap"]

    if current and not tail:
        ending = current[-1]["gap"]
        if not new and head:
            # Deleting the last block: the file's ending moves back one block.
            head[-1]["gap"] = ending
        elif new and index == end and head:
            # Appending: the file's ending moves onto the new last block, and
            # what was the last block needs a separator in its place.
            if new[-1]["gap"] is None:
                new[-1]["gap"] = ending
            head[-1]["gap"] = DEFAULT_GAP

    for block in new:
        if block["gap"] is None:
            block["gap"] = DEFAULT_GAP

    return join_blocks(head + new + tail), index


def _incoming(block):
    """One caller-supplied block, normalised: `raw` carries no line ending.

    A trailing ending on `raw` is not dropped -- it moves to the front of the
    gap, so what the caller sent is what the file gets. `gap` stays None when
    the caller named nothing, which is how `splice_blocks` tells the two apart.
    """
    raw = block.get("raw", "")
    trailing = ""
    while True:
        raw, ending = _split_trailing_newline(raw)
        if not ending:
            break
        trailing = ending + trailing

    gap = block.get("gap")
    if trailing:
        gap = trailing + (gap or "")
    return {"raw": raw, "gap": gap}


def _consume(lines, i):
    """Find where the block starting at `i` ends, and what kind it is.

    Returns `(end, type)` with `end` exclusive. Checked in precedence order:
    a fence swallows anything inside it, and a rule is decided before a bullet
    list so `---` is not read as an empty item.
    """
    line = lines[i]

    if _FENCE.match(line):
        return _consume_fence(lines, i), "code"
    if _HTML_COMMENT.match(line):
        return _consume_until(lines, i, "-->"), "html"
    if _HTML_TAG.match(line):
        return _consume_while(lines, i + 1, lambda _: True), "html"
    if _RULE.match(line):
        return i + 1, "rule"
    if _ATX.match(line):
        return i + 1, "heading"

    table_end = _consume_table(lines, i)
    if table_end:
        return table_end, "table"

    if _QUOTE.match(line):
        return _consume_while(lines, i + 1, lambda _: True), "quote"
    if _BULLET.match(line) or _ORDERED.match(line):
        return _consume_list(lines, i), "list"
    return _consume_paragraph(lines, i)


def _consume_fence(lines, i):
    """A fenced block runs to its closing fence, or to the end of the file."""
    opening = _FENCE.match(lines[i])
    marker = opening.group(1) if opening else "```"
    closing = re.compile(r"^ {0,3}%s%s*[ \t]*\r?\n?$" % (re.escape(marker), re.escape(marker[0])))
    for j in range(i + 1, len(lines)):
        if closing.match(lines[j]):
            return j + 1
    return len(lines)


def _consume_until(lines, i, needle):
    for j in range(i, len(lines)):
        if needle in lines[j]:
            return j + 1
    return len(lines)


def _consume_while(lines, i, keep):
    """Take lines from `i` while they are non-blank and `keep` accepts them."""
    j = i
    while j < len(lines) and not _is_blank(lines[j]) and keep(lines[j]):
        j += 1
    return j


def _consume_list(lines, i):
    """A list runs on through blank lines only while indented content follows."""
    # Its own markers do not interrupt it, and neither does an unindented lazy
    # continuation line -- both are the list carrying on.
    j = _consume_while(lines, i + 1, lambda line: not _starts_other_block(line, in_list=True))
    while j < len(lines):
        blanks = j
        while blanks < len(lines) and _is_blank(lines[blanks]):
            blanks += 1
        if blanks == j or blanks >= len(lines) or not _INDENTED.match(lines[blanks]):
            break
        j = _consume_while(lines, blanks, lambda _: True)
    return j


def _consume_paragraph(lines, i):
    """A paragraph runs to a blank line, an interrupting block, or a setext rule."""
    j = i + 1
    while j < len(lines) and not _is_blank(lines[j]):
        if _SETEXT.match(lines[j]):
            # Underlined heading: it wins over a thematic break here, because a
            # `---` directly under text underlines it rather than dividing it.
            return j + 1, "heading"
        if _starts_other_block(lines[j]):
            break
        j += 1
    return j, "paragraph"


def _starts_other_block(line, in_list=False):
    """Whether this line interrupts whatever block is already open."""
    if not in_list and (_BULLET.match(line) or _ORDERED.match(line)):
        return True
    return bool(
        _ATX.match(line)
        or _FENCE.match(line)
        or _RULE.match(line)
        or _QUOTE.match(line)
        or _HTML_COMMENT.match(line)
    )


def _is_blank(line):
    return bool(_BLANK.match(line))


def _split_trailing_newline(text):
    """Split a block's text from its own line ending, which belongs to the gap."""
    for ending in ("\r\n", "\n", "\r"):
        if text.endswith(ending):
            return text[: -len(ending)], ending
    return text, ""


# --- tables ------------------------------------------------------------------


def _consume_table(lines, i):
    """End of the table starting at `i`, or None if this is not a table.

    A pipe line is only a table when a delimiter row follows it **and** matches
    it in column count, which is what GFM requires -- otherwise the row is
    ordinary text that happens to contain pipes.
    """
    if i + 1 >= len(lines) or "|" not in lines[i]:
        return None
    align = _parse_delimiter(lines[i + 1])
    if align is None or len(align) != len(_split_row(lines[i])):
        return None
    j = i + 2
    while j < len(lines) and not _is_blank(lines[j]) and "|" in lines[j]:
        j += 1
    return j


def parse_table(raw):
    """Read a table block into head, align and rows. None if it is not a table."""
    lines = raw.splitlines(keepends=True)
    if _consume_table(lines, 0) is None:
        return None
    return {
        "head": _split_row(lines[0]),
        "align": _parse_delimiter(lines[1]),
        "rows": [_split_row(line) for line in lines[2:]],
    }


def serialise_table(table):
    """Write a table back as markdown with every column padded to its widest cell.

    This is the one place the file is deliberately reformatted, and it is the
    feature: a grid edit comes back aligned rather than ragged.
    """
    head = [_escape_cell(cell) for cell in table.get("head", [])]
    rows = [[_escape_cell(cell) for cell in row] for row in table.get("rows", [])]
    align = list(table.get("align", []))

    columns = max([len(head)] + [len(row) for row in rows])
    align += [""] * (columns - len(align))
    widths = [
        max([MIN_COLUMN_WIDTH] + [len(row[column]) for row in [head] + rows if column < len(row)])
        for column in range(columns)
    ]

    lines = [_write_row(head, widths, align), _write_row(_write_delimiters(align, widths), widths)]
    lines += [_write_row(row, widths, align) for row in rows]
    return "\n".join(lines)


def _write_row(cells, widths, align=None):
    """One row, each cell padded to its column -- and to that column's side.

    A right-aligned column is padded on the left, so a column of numbers lines
    up on its last digit in the file as well as on screen. That is the whole
    reason someone marks the column right-aligned. Delimiter cells arrive at
    exactly their width and pass through either way.
    """
    padded = []
    for column, width in enumerate(widths):
        cell = cells[column] if column < len(cells) else ""
        marker = align[column] if align and column < len(align) else ""
        if marker == "right":
            padded.append(cell.rjust(width))
        elif marker == "center":
            padded.append(cell.center(width))
        else:
            padded.append(cell.ljust(width))
    return "| " + " | ".join(padded) + " |"


def _write_delimiters(align, widths):
    dashes = []
    for column, width in enumerate(widths):
        marker = align[column] if column < len(align) else ""
        if marker == "left":
            dashes.append(":" + "-" * (width - 1))
        elif marker == "right":
            dashes.append("-" * (width - 1) + ":")
        elif marker == "center":
            dashes.append(":" + "-" * (width - 2) + ":")
        else:
            dashes.append("-" * width)
    return dashes


def _parse_delimiter(line):
    """The alignment of each column, or None when this is not a delimiter row."""
    if "|" not in line:
        return None
    cells = _split_row(line)
    if not cells or not all(_DELIMITER_CELL.match(cell) for cell in cells):
        return None
    align = []
    for cell in cells:
        left, right = cell.startswith(":"), cell.endswith(":")
        align.append("center" if left and right else "left" if left else "right" if right else "")
    return align


def _split_row(line):
    """Cells of one table row. Escaped pipes stay escaped and stay in the cell."""
    row = line.strip()
    if row.startswith("|"):
        row = row[1:]
    if row.endswith("|") and not row.endswith("\\|"):
        row = row[:-1]
    return [cell.strip() for cell in _UNESCAPED_PIPE.split(row)]


def _escape_cell(cell):
    """One file line: any pipe escaped exactly once, any newline as `CELL_BREAK`.

    Both directions of this translation are somebody's job -- the pipe is
    unescaped before it is escaped so the pass is idempotent, and `<br>` reads
    back as a newline in `editor.js`. A cell already holding `<br>` therefore
    survives untouched, which is what keeps a saved table byte-stable.
    """
    escaped = cell.replace("\\|", "|").replace("|", "\\|")
    return _CELL_NEWLINE.sub(CELL_BREAK, escaped)


# --- writing single cells -----------------------------------------------------
#
# A finer door still: a write names cells rather than a run of blocks, so two
# people in two cells of one table stop being a conflict the way two people in
# two blocks already stopped being one. The guard shrinks with the unit -- each
# cell carries the text it believes it is replacing, and only a cell whose own
# text moved is refused.
#
# `raw` is regenerated by `serialise_table` either way, so this changes nothing
# about how a table reaches the file. It changes what a refusal costs.


def same_cell(one, other):
    """Whether two cell values mean the same cell text.

    Compared **as the file would spell them**, because the two sides do not
    spell them alike: a cell read out of the file carries `<br>` and escaped
    pipes, and one typed in the editor carries real newlines and bare ones.
    `serialise_table` normalises both on the way in, so a guard that compared
    the strings raw would refuse a cell nobody had touched.
    """
    return _escape_cell(str(one or "")) == _escape_cell(str(other or ""))


def find_table(blocks, at, head):
    """Index of the table block a cell write is aimed at. Refuses if that is not one place.

    `find_run`'s reasoning, one construct down: try `at`, then search. What
    identifies the table through an edit is its **header row** -- the cells
    below it are exactly what is being written, so they cannot also be the
    name. Two tables with the same header are genuinely ambiguous and are
    refused rather than guessed at.
    """
    def matches(block):
        table = block.get("table")
        return bool(table) and len(table["head"]) == len(head) and all(
            same_cell(one, other) for one, other in zip(table["head"], head))

    if 0 <= at < len(blocks) and matches(blocks[at]):
        return at

    found = [index for index, block in enumerate(blocks) if matches(block)]
    if len(found) == 1:
        return found[0]
    if not found:
        raise SpliceRefused("gone", "That table is not in the file any more.")
    raise SpliceRefused(
        "ambiguous",
        f"{len(found)} tables in the file have that header, so which one was meant is a guess.",
    )


def write_cells(table, cells):
    """Apply cell writes to a copy of `table`. Refuses when a named cell moved.

    Each cell is `{r, c, expect, text}`, with `r` of -1 for the header. The
    refusal is per cell and says which one: a write naming three cells lands
    none of them if one is stale, because a half-applied grid is a table nobody
    asked for.

    Structure is not writable here on purpose -- no row is added, none is
    removed, and the alignment is left alone. Those change what every other cell
    is addressed by, so they stay a whole-block write.
    """
    fresh = {
        "head": list(table.get("head", [])),
        "align": list(table.get("align", [])),
        "rows": [list(row) for row in table.get("rows", [])],
    }
    for cell in cells:
        r, column = cell["r"], cell["c"]
        rows = fresh["head"] if r == -1 else (fresh["rows"][r] if 0 <= r < len(fresh["rows"]) else None)
        if rows is None or not 0 <= column < len(rows):
            raise SpliceRefused(
                "out of range",
                f"{_cell_name(r, column)} is not in this table any more.",
            )
        if not same_cell(rows[column], cell.get("expect", "")):
            raise SpliceRefused(
                "stale",
                f"{_cell_name(r, column)} changed since it was read. Nothing was written.",
            )
        rows[column] = cell.get("text", "")
    return fresh


def _cell_name(r, column):
    """How a refusal names a cell, counting from 1 the way the grid is read."""
    where = "the header" if r == -1 else f"row {r + 1}"
    return f"Column {column + 1} of {where}"


# --- rendering ---------------------------------------------------------------

# A mermaid fence is handed to the frontend as a container holding its own
# source, never as a diagram: drawing one needs SVG, so it is the one part of
# this feature that has to happen client-side.
MERMAID_LANGUAGE = "mermaid"
MERMAID_CLASS = "mermaid-source"


class _Renderer(RendererHTML):
    """Stock HTML rendering, with mermaid fences left for the frontend to draw."""

    def fence(self, tokens, idx, options, env):
        info = tokens[idx].info.strip().split(maxsplit=1)
        if info and info[0].lower() == MERMAID_LANGUAGE:
            return f'<pre class="{MERMAID_CLASS}">{escape(tokens[idx].content)}</pre>\n'
        return super().fence(tokens, idx, options, env)


def _build_renderer():
    """One markdown-it, GFM-ish, configured once.

    `html=True` because the sprint template relies on raw HTML -- `<u>` around
    deliverable headings and a `<details>` reference block. The usual reason to
    disable it does not apply here: these are your own files, on localhost, with
    no untrusted input anywhere near them. Do not "fix" this without reading
    templates/sprint.md first.

    linkify is off so the app needs no third dependency for it; a bare URL is
    still a link when written as one.

    `enabled=True` on the tasklists plugin drops the `disabled` attribute the
    plugin adds by default, so a `- [ ]` can be ticked. It renders the checkbox;
    what a tick *means* is the frontend's problem, and there it is a rewrite of
    the block's own markdown -- the file is still the record.
    """
    md = MarkdownIt("gfm-like", {"html": True, "linkify": False}, renderer_cls=_Renderer)
    return md.use(tasklists_plugin, enabled=True)


_RENDERER = _build_renderer()


def render_block(block):
    """Render one block to HTML for display. Never mutates `raw`."""
    return _RENDERER.render(block["raw"])


def document_blocks(text):
    """Split `text` into blocks and attach each one's rendered HTML."""
    blocks = split_blocks(text)
    for block in blocks:
        block["html"] = render_block(block)
    return blocks
